<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><?= htmlspecialchars($subject ?? 'Pearl Framework Notification', ENT_QUOTES, 'UTF-8') ?></title>
    <style>
        body {
            margin: 0;
            padding: 0;
            background-color: #0f172a;
            color: #e2e8f0;
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif;
            line-height: 1.6;
        }
        .wrapper {
            width: 100%;
            background-color: #090d16;
            padding: 40px 0;
        }
        .container {
            max-width: 580px;
            margin: 0 auto;
            background-color: #111827;
            border: 1px solid #1f2937;
            border-radius: 8px;
            overflow: hidden;
        }
        .header {
            padding: 28px 32px;
            background-color: #161f33;
            border-bottom: 1px solid #1f2937;
            text-align: left;
        }
        .logo {
            font-size: 20px;
            font-weight: 700;
            letter-spacing: -0.025em;
            color: #38bdf8;
            text-decoration: none;
        }
        .body {
            padding: 32px;
            color: #cbd5e1;
            font-size: 15px;
        }
        .footer {
            padding: 24px 32px;
            background-color: #0d131f;
            border-top: 1px solid #1f2937;
            text-align: center;
            font-size: 12px;
            color: #64748b;
        }
        .btn {
            display: inline-block;
            background-color: #0284c7;
            color: #ffffff;
            font-weight: 600;
            font-size: 14px;
            padding: 10px 20px;
            text-decoration: none;
            border-radius: 6px;
            margin-top: 16px;
        }
    </style>
</head>
<body>
    <div class="wrapper">
        <div class="container">
            <div class="header">
                <a href="#" class="logo">PEARL</a>
            </div>
            <div class="body">
                <?= $content ?? '' ?>
            </div>
            <div class="footer">
                &copy; <?= date('Y') ?> Pearl Framework. All rights reserved.<br>
                This automated message was generated by Pearl.
            </div>
        </div>
    </div>
</body>
</html>
