<?php
/**
 * Pearl Framework — Vite Asset Helper
 *
 * Outputs the correct <script>/<link> tags for an entry point, in
 * either mode:
 *
 *   production — reads public/build/.vite/manifest.json (generated by
 *                `npm run build` since vite.config.js has manifest:true),
 *                outputs the hashed built file + its CSS imports.
 *   development — outputs tags pointing at the running Vite dev server
 *                (`npm run dev`), for hot module reloading.
 *
 * Mode is decided by whether the manifest file exists, not by
 * APP_ENV — this way a production-mode build still works locally if
 * you run `npm run build` instead of `npm run dev`, and vice versa.
 *
 * Depends on: pearl/paths.php (public_path), bootstrap.php (env).
 *
 * See pearl/FUNCTIONS.md for the ownership registry.
 */

declare(strict_types=1);

if (!function_exists('public_path')) {
    throw new RuntimeException('pearl/paths.php must be required before pearl/vite.php.');
}

/**
 * Output <script>/<link> tags for a Vite entry point (e.g. 'main.js').
 * Echoes directly (like pearl_view() does for response body) so it
 * can be used inline in a layout's <head> with <?= vite('main.js') ?>.
 */
if (!function_exists('vite')) {
    function vite(string $entry): string
    {
        $manifestPath = public_path('build/.vite/manifest.json');

        if (is_file($manifestPath)) {
            return vite_production_tags($entry, $manifestPath);
        }

        return vite_dev_tags($entry);
    }
}

/**
 * Resolves the base URL for built assets, respecting ASSET_URL env
 * and auto-detecting subfolder deployments (e.g. XAMPP htdocs subfolders).
 */
if (!function_exists('vite_asset_url')) {
    function vite_asset_url(string $path = ''): string
    {
        $customBase = env('ASSET_URL');
        if ($customBase !== null && $customBase !== '') {
            $base = rtrim((string) $customBase, '/') . '/build';
            return $path === '' ? $base : $base . '/' . ltrim($path, '/');
        }

        $scriptName = $_SERVER['SCRIPT_NAME'] ?? '';
        $subfolder = rtrim(str_replace('\\', '/', dirname($scriptName)), '/');

        if ($subfolder !== '' && $subfolder !== '.') {
            $base = $subfolder . '/build';
        } else {
            $base = '/build';
        }

        return $path === '' ? $base : $base . '/' . ltrim($path, '/');
    }
}

/**
 * Production mode: resolve the entry through the manifest, including
 * any CSS files Vite associated with it (e.g. main.css imported from
 * main.js ends up as a "css" array on the main.js manifest entry).
 */
if (!function_exists('vite_production_tags')) {
    function vite_production_tags(string $entry, string $manifestPath): string
    {
        $manifest = json_decode((string) file_get_contents($manifestPath), true);

        if (!is_array($manifest) || !isset($manifest[$entry])) {
            return "<!-- vite: entry not found in manifest: " . htmlspecialchars($entry, ENT_QUOTES) . " -->";
        }

        $entryData = $manifest[$entry];
        $tags = [];

        foreach ($entryData['css'] ?? [] as $cssFile) {
            $tags[] = '<link rel="stylesheet" href="' . htmlspecialchars(vite_asset_url($cssFile), ENT_QUOTES) . '">';
        }

        $tags[] = '<script type="module" src="' . htmlspecialchars(vite_asset_url($entryData['file']), ENT_QUOTES) . '"></script>';

        return implode("\n    ", $tags);
    }
}

/**
 * Development mode: point at the Vite dev server (npm run dev),
 * including the @vite/client script HMR needs.
 */
if (!function_exists('vite_dev_tags')) {
    function vite_dev_tags(string $entry): string
    {
        $host = env('VITE_HOST', 'localhost');
        $port = env('VITE_PORT', '5173');
        $base = "http://{$host}:{$port}";

        return implode("\n    ", [
            '<script type="module" src="' . $base . '/@vite/client"></script>',
            '<script type="module" src="' . $base . '/' . htmlspecialchars($entry, ENT_QUOTES) . '"></script>',
        ]);
    }
}
